apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: lubbibot
  name: lubbibot
  namespace: public
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: lubbibot
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lubbibot
    spec:
      containers:
        - image: krisnova/lubbibot:latest
          env:
          - name: PHOTOPRISMCONN
            value: "https://photos.nivenly.com"
          - name: PHOTOPRISMALBUM
            value: "aqpheqa1sz2bad6m"
          envFrom:
            - secretRef:
                name: deployments
                optional: false
          imagePullPolicy: Always
          name: lubbibot
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30